
package com.imperialm.imimserservices.ssrs;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-02T01:29:56.287-04:00
 * Generated source version: 3.1.12
 * 
 */
public final class ReportExecutionServiceSoap_ReportExecutionServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportExecutionService");

    private ReportExecutionServiceSoap_ReportExecutionServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ReportExecutionService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ReportExecutionService ss = new ReportExecutionService(wsdlURL, SERVICE_NAME);
        ReportExecutionServiceSoap port = ss.getReportExecutionServiceSoap();  
        
        {
        System.out.println("Invoking render2...");
        java.lang.String _render2_format = "";
        java.lang.String _render2_deviceInfo = "";
        PageCountMode _render2_paginationMode = null;
        javax.xml.ws.Holder<byte[]> _render2_result = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _render2_extension = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _render2_mimeType = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _render2_encoding = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<ArrayOfWarning> _render2_warnings = new javax.xml.ws.Holder<ArrayOfWarning>();
        javax.xml.ws.Holder<ArrayOfString> _render2_streamIds = new javax.xml.ws.Holder<ArrayOfString>();
        port.render2(_render2_format, _render2_deviceInfo, _render2_paginationMode, _render2_result, _render2_extension, _render2_mimeType, _render2_encoding, _render2_warnings, _render2_streamIds);

        System.out.println("render2._render2_result=" + _render2_result.value);
        System.out.println("render2._render2_extension=" + _render2_extension.value);
        System.out.println("render2._render2_mimeType=" + _render2_mimeType.value);
        System.out.println("render2._render2_encoding=" + _render2_encoding.value);
        System.out.println("render2._render2_warnings=" + _render2_warnings.value);
        System.out.println("render2._render2_streamIds=" + _render2_streamIds.value);

        }
        {
        System.out.println("Invoking getRenderResource...");
        java.lang.String _getRenderResource_format = "";
        java.lang.String _getRenderResource_deviceInfo = "";
        javax.xml.ws.Holder<byte[]> _getRenderResource_result = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _getRenderResource_mimeType = new javax.xml.ws.Holder<java.lang.String>();
        port.getRenderResource(_getRenderResource_format, _getRenderResource_deviceInfo, _getRenderResource_result, _getRenderResource_mimeType);

        System.out.println("getRenderResource._getRenderResource_result=" + _getRenderResource_result.value);
        System.out.println("getRenderResource._getRenderResource_mimeType=" + _getRenderResource_mimeType.value);

        }
        {
        System.out.println("Invoking setExecutionParameters2...");
        com.imperialm.imimserservices.ssrs.ArrayOfParameterValue _setExecutionParameters2_parameters = null;
        java.lang.String _setExecutionParameters2_parameterLanguage = "";
        com.imperialm.imimserservices.ssrs.ExecutionInfo2 _setExecutionParameters2__return = port.setExecutionParameters2(_setExecutionParameters2_parameters, _setExecutionParameters2_parameterLanguage);
        System.out.println("setExecutionParameters2.result=" + _setExecutionParameters2__return);


        }
        {
        System.out.println("Invoking setExecutionParameters3...");
        ArrayOfParameterValue _setExecutionParameters3_parameters = null;
        java.lang.String _setExecutionParameters3_parameterLanguage = "";
        ExecutionInfo3 _setExecutionParameters3__return = port.setExecutionParameters3(_setExecutionParameters3_parameters, _setExecutionParameters3_parameterLanguage);
        System.out.println("setExecutionParameters3.result=" + _setExecutionParameters3__return);


        }
        {
        System.out.println("Invoking loadDrillthroughTarget...");
        java.lang.String _loadDrillthroughTarget_drillthroughID = "";
        com.imperialm.imimserservices.ssrs.ExecutionInfo _loadDrillthroughTarget__return = port.loadDrillthroughTarget(_loadDrillthroughTarget_drillthroughID);
        System.out.println("loadDrillthroughTarget.result=" + _loadDrillthroughTarget__return);


        }
        {
        System.out.println("Invoking getDocumentMap...");
        com.imperialm.imimserservices.ssrs.DocumentMapNode _getDocumentMap__return = port.getDocumentMap();
        System.out.println("getDocumentMap.result=" + _getDocumentMap__return);


        }
        {
        System.out.println("Invoking listRenderingExtensions...");
        com.imperialm.imimserservices.ssrs.ArrayOfExtension _listRenderingExtensions__return = port.listRenderingExtensions();
        System.out.println("listRenderingExtensions.result=" + _listRenderingExtensions__return);


        }
        {
        System.out.println("Invoking listSecureMethods...");
        com.imperialm.imimserservices.ssrs.ArrayOfString _listSecureMethods__return = port.listSecureMethods();
        System.out.println("listSecureMethods.result=" + _listSecureMethods__return);


        }
        {
        System.out.println("Invoking resetExecution3...");
        com.imperialm.imimserservices.ssrs.ExecutionInfo3 _resetExecution3__return = port.resetExecution3();
        System.out.println("resetExecution3.result=" + _resetExecution3__return);


        }
        {
        System.out.println("Invoking setExecutionParameters...");
        ArrayOfParameterValue _setExecutionParameters_parameters = null;
        java.lang.String _setExecutionParameters_parameterLanguage = "";
        ExecutionInfo _setExecutionParameters__return = port.setExecutionParameters(_setExecutionParameters_parameters, _setExecutionParameters_parameterLanguage);
        System.out.println("setExecutionParameters.result=" + _setExecutionParameters__return);


        }
        {
        System.out.println("Invoking deliverReportItem...");
        java.lang.String _deliverReportItem_format = "";
        java.lang.String _deliverReportItem_deviceInfo = "";
        com.imperialm.imimserservices.ssrs.ExtensionSettings _deliverReportItem_extensionSettings = null;
        java.lang.String _deliverReportItem_description = "";
        java.lang.String _deliverReportItem_eventType = "";
        java.lang.String _deliverReportItem_matchData = "";
        port.deliverReportItem(_deliverReportItem_format, _deliverReportItem_deviceInfo, _deliverReportItem_extensionSettings, _deliverReportItem_description, _deliverReportItem_eventType, _deliverReportItem_matchData);


        }
        {
        System.out.println("Invoking resetExecution2...");
        com.imperialm.imimserservices.ssrs.ExecutionInfo2 _resetExecution2__return = port.resetExecution2();
        System.out.println("resetExecution2.result=" + _resetExecution2__return);


        }
        {
        System.out.println("Invoking sort2...");
        java.lang.String _sort2_sortItem = "";
        SortDirectionEnum _sort2_direction = null;
        boolean _sort2_clear = false;
        PageCountMode _sort2_paginationMode = null;
        javax.xml.ws.Holder<java.lang.Integer> _sort2_pageNumber = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _sort2_reportItem = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<ExecutionInfo2> _sort2_executionInfo = new javax.xml.ws.Holder<ExecutionInfo2>();
        port.sort2(_sort2_sortItem, _sort2_direction, _sort2_clear, _sort2_paginationMode, _sort2_pageNumber, _sort2_reportItem, _sort2_executionInfo);

        System.out.println("sort2._sort2_pageNumber=" + _sort2_pageNumber.value);
        System.out.println("sort2._sort2_reportItem=" + _sort2_reportItem.value);
        System.out.println("sort2._sort2_executionInfo=" + _sort2_executionInfo.value);

        }
        {
        System.out.println("Invoking navigateBookmark...");
        java.lang.String _navigateBookmark_bookmarkID = "";
        javax.xml.ws.Holder<java.lang.Integer> _navigateBookmark_pageNumber = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _navigateBookmark_uniqueName = new javax.xml.ws.Holder<java.lang.String>();
        port.navigateBookmark(_navigateBookmark_bookmarkID, _navigateBookmark_pageNumber, _navigateBookmark_uniqueName);

        System.out.println("navigateBookmark._navigateBookmark_pageNumber=" + _navigateBookmark_pageNumber.value);
        System.out.println("navigateBookmark._navigateBookmark_uniqueName=" + _navigateBookmark_uniqueName.value);

        }
        {
        System.out.println("Invoking sort3...");
        java.lang.String _sort3_sortItem = "";
        com.imperialm.imimserservices.ssrs.SortDirectionEnum _sort3_direction = null;
        boolean _sort3_clear = false;
        com.imperialm.imimserservices.ssrs.PageCountMode _sort3_paginationMode = null;
        javax.xml.ws.Holder<java.lang.Integer> _sort3_pageNumber = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _sort3_reportItem = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<ExecutionInfo3> _sort3_executionInfo = new javax.xml.ws.Holder<ExecutionInfo3>();
        port.sort3(_sort3_sortItem, _sort3_direction, _sort3_clear, _sort3_paginationMode, _sort3_pageNumber, _sort3_reportItem, _sort3_executionInfo);

        System.out.println("sort3._sort3_pageNumber=" + _sort3_pageNumber.value);
        System.out.println("sort3._sort3_reportItem=" + _sort3_reportItem.value);
        System.out.println("sort3._sort3_executionInfo=" + _sort3_executionInfo.value);

        }
        {
        System.out.println("Invoking logoff...");
        port.logoff();


        }
        {
        System.out.println("Invoking loadReport...");
        java.lang.String _loadReport_report = "";
        java.lang.String _loadReport_historyID = "";
        ExecutionInfo _loadReport__return = port.loadReport(_loadReport_report, _loadReport_historyID);
        System.out.println("loadReport.result=" + _loadReport__return);


        }
        {
        System.out.println("Invoking loadReportDefinition...");
        byte[] _loadReportDefinition_definition = new byte[0];
        javax.xml.ws.Holder<ExecutionInfo> _loadReportDefinition_executionInfo = new javax.xml.ws.Holder<ExecutionInfo>();
        javax.xml.ws.Holder<ArrayOfWarning> _loadReportDefinition_warnings = new javax.xml.ws.Holder<ArrayOfWarning>();
        port.loadReportDefinition(_loadReportDefinition_definition, _loadReportDefinition_executionInfo, _loadReportDefinition_warnings);

        System.out.println("loadReportDefinition._loadReportDefinition_executionInfo=" + _loadReportDefinition_executionInfo.value);
        System.out.println("loadReportDefinition._loadReportDefinition_warnings=" + _loadReportDefinition_warnings.value);

        }
        {
        System.out.println("Invoking loadReport2...");
        java.lang.String _loadReport2_report = "";
        java.lang.String _loadReport2_historyID = "";
        com.imperialm.imimserservices.ssrs.ExecutionInfo2 _loadReport2__return = port.loadReport2(_loadReport2_report, _loadReport2_historyID);
        System.out.println("loadReport2.result=" + _loadReport2__return);


        }
        {
        System.out.println("Invoking loadReport3...");
        java.lang.String _loadReport3_report = "";
        java.lang.String _loadReport3_historyID = "";
        com.imperialm.imimserservices.ssrs.ExecutionInfo3 _loadReport3__return = port.loadReport3(_loadReport3_report, _loadReport3_historyID);
        System.out.println("loadReport3.result=" + _loadReport3__return);


        }
        {
        System.out.println("Invoking loadDrillthroughTarget3...");
        java.lang.String _loadDrillthroughTarget3_drillthroughID = "";
        com.imperialm.imimserservices.ssrs.ExecutionInfo3 _loadDrillthroughTarget3__return = port.loadDrillthroughTarget3(_loadDrillthroughTarget3_drillthroughID);
        System.out.println("loadDrillthroughTarget3.result=" + _loadDrillthroughTarget3__return);


        }
        {
        System.out.println("Invoking loadDrillthroughTarget2...");
        java.lang.String _loadDrillthroughTarget2_drillthroughID = "";
        com.imperialm.imimserservices.ssrs.ExecutionInfo2 _loadDrillthroughTarget2__return = port.loadDrillthroughTarget2(_loadDrillthroughTarget2_drillthroughID);
        System.out.println("loadDrillthroughTarget2.result=" + _loadDrillthroughTarget2__return);


        }
        {
        System.out.println("Invoking navigateDocumentMap...");
        java.lang.String _navigateDocumentMap_docMapID = "";
        int _navigateDocumentMap__return = port.navigateDocumentMap(_navigateDocumentMap_docMapID);
        System.out.println("navigateDocumentMap.result=" + _navigateDocumentMap__return);


        }
        {
        System.out.println("Invoking setExecutionCredentials3...");
        ArrayOfDataSourceCredentials _setExecutionCredentials3_credentials = null;
        ExecutionInfo3 _setExecutionCredentials3__return = port.setExecutionCredentials3(_setExecutionCredentials3_credentials);
        System.out.println("setExecutionCredentials3.result=" + _setExecutionCredentials3__return);


        }
        {
        System.out.println("Invoking setExecutionCredentials2...");
        ArrayOfDataSourceCredentials _setExecutionCredentials2_credentials = null;
        ExecutionInfo2 _setExecutionCredentials2__return = port.setExecutionCredentials2(_setExecutionCredentials2_credentials);
        System.out.println("setExecutionCredentials2.result=" + _setExecutionCredentials2__return);


        }
        {
        System.out.println("Invoking render...");
        java.lang.String _render_format = "";
        java.lang.String _render_deviceInfo = "";
        javax.xml.ws.Holder<byte[]> _render_result = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _render_extension = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _render_mimeType = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _render_encoding = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<ArrayOfWarning> _render_warnings = new javax.xml.ws.Holder<ArrayOfWarning>();
        javax.xml.ws.Holder<ArrayOfString> _render_streamIds = new javax.xml.ws.Holder<ArrayOfString>();
        port.render(_render_format, _render_deviceInfo, _render_result, _render_extension, _render_mimeType, _render_encoding, _render_warnings, _render_streamIds);

        System.out.println("render._render_result=" + _render_result.value);
        System.out.println("render._render_extension=" + _render_extension.value);
        System.out.println("render._render_mimeType=" + _render_mimeType.value);
        System.out.println("render._render_encoding=" + _render_encoding.value);
        System.out.println("render._render_warnings=" + _render_warnings.value);
        System.out.println("render._render_streamIds=" + _render_streamIds.value);

        }
        {
        System.out.println("Invoking getExecutionInfo...");
        ExecutionInfo _getExecutionInfo__return = port.getExecutionInfo();
        System.out.println("getExecutionInfo.result=" + _getExecutionInfo__return);


        }
        {
        System.out.println("Invoking loadReportDefinition3...");
        byte[] _loadReportDefinition3_definition = new byte[0];
        javax.xml.ws.Holder<ExecutionInfo3> _loadReportDefinition3_executionInfo = new javax.xml.ws.Holder<ExecutionInfo3>();
        javax.xml.ws.Holder<ArrayOfWarning> _loadReportDefinition3_warnings = new javax.xml.ws.Holder<ArrayOfWarning>();
        port.loadReportDefinition3(_loadReportDefinition3_definition, _loadReportDefinition3_executionInfo, _loadReportDefinition3_warnings);

        System.out.println("loadReportDefinition3._loadReportDefinition3_executionInfo=" + _loadReportDefinition3_executionInfo.value);
        System.out.println("loadReportDefinition3._loadReportDefinition3_warnings=" + _loadReportDefinition3_warnings.value);

        }
        {
        System.out.println("Invoking findString...");
        int _findString_startPage = 0;
        int _findString_endPage = 0;
        java.lang.String _findString_findValue = "";
        int _findString__return = port.findString(_findString_startPage, _findString_endPage, _findString_findValue);
        System.out.println("findString.result=" + _findString__return);


        }
        {
        System.out.println("Invoking logonUser...");
        java.lang.String _logonUser_userName = "";
        java.lang.String _logonUser_password = "";
        java.lang.String _logonUser_authority = "";
        port.logonUser(_logonUser_userName, _logonUser_password, _logonUser_authority);


        }
        {
        System.out.println("Invoking toggleItem...");
        java.lang.String _toggleItem_toggleID = "";
        boolean _toggleItem__return = port.toggleItem(_toggleItem_toggleID);
        System.out.println("toggleItem.result=" + _toggleItem__return);


        }
        {
        System.out.println("Invoking sort...");
        java.lang.String _sort_sortItem = "";
        SortDirectionEnum _sort_direction = null;
        boolean _sort_clear = false;
        javax.xml.ws.Holder<java.lang.Integer> _sort_pageNumber = new javax.xml.ws.Holder<java.lang.Integer>();
        javax.xml.ws.Holder<java.lang.String> _sort_reportItem = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.Integer> _sort_numPages = new javax.xml.ws.Holder<java.lang.Integer>();
        port.sort(_sort_sortItem, _sort_direction, _sort_clear, _sort_pageNumber, _sort_reportItem, _sort_numPages);

        System.out.println("sort._sort_pageNumber=" + _sort_pageNumber.value);
        System.out.println("sort._sort_reportItem=" + _sort_reportItem.value);
        System.out.println("sort._sort_numPages=" + _sort_numPages.value);

        }
        {
        System.out.println("Invoking loadReportDefinition2...");
        byte[] _loadReportDefinition2_definition = new byte[0];
        javax.xml.ws.Holder<ExecutionInfo2> _loadReportDefinition2_executionInfo = new javax.xml.ws.Holder<ExecutionInfo2>();
        javax.xml.ws.Holder<ArrayOfWarning> _loadReportDefinition2_warnings = new javax.xml.ws.Holder<ArrayOfWarning>();
        port.loadReportDefinition2(_loadReportDefinition2_definition, _loadReportDefinition2_executionInfo, _loadReportDefinition2_warnings);

        System.out.println("loadReportDefinition2._loadReportDefinition2_executionInfo=" + _loadReportDefinition2_executionInfo.value);
        System.out.println("loadReportDefinition2._loadReportDefinition2_warnings=" + _loadReportDefinition2_warnings.value);

        }
        {
        System.out.println("Invoking resetExecution...");
        ExecutionInfo _resetExecution__return = port.resetExecution();
        System.out.println("resetExecution.result=" + _resetExecution__return);


        }
        {
        System.out.println("Invoking setExecutionCredentials...");
        ArrayOfDataSourceCredentials _setExecutionCredentials_credentials = null;
        ExecutionInfo _setExecutionCredentials__return = port.setExecutionCredentials(_setExecutionCredentials_credentials);
        System.out.println("setExecutionCredentials.result=" + _setExecutionCredentials__return);


        }
        {
        System.out.println("Invoking getExecutionInfo3...");
        ExecutionInfo3 _getExecutionInfo3__return = port.getExecutionInfo3();
        System.out.println("getExecutionInfo3.result=" + _getExecutionInfo3__return);


        }
        {
        System.out.println("Invoking getExecutionInfo2...");
        ExecutionInfo2 _getExecutionInfo2__return = port.getExecutionInfo2();
        System.out.println("getExecutionInfo2.result=" + _getExecutionInfo2__return);


        }
        {
        System.out.println("Invoking renderStream...");
        java.lang.String _renderStream_format = "";
        java.lang.String _renderStream_streamID = "";
        java.lang.String _renderStream_deviceInfo = "";
        javax.xml.ws.Holder<byte[]> _renderStream_result = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _renderStream_encoding = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _renderStream_mimeType = new javax.xml.ws.Holder<java.lang.String>();
        port.renderStream(_renderStream_format, _renderStream_streamID, _renderStream_deviceInfo, _renderStream_result, _renderStream_encoding, _renderStream_mimeType);

        System.out.println("renderStream._renderStream_result=" + _renderStream_result.value);
        System.out.println("renderStream._renderStream_encoding=" + _renderStream_encoding.value);
        System.out.println("renderStream._renderStream_mimeType=" + _renderStream_mimeType.value);

        }

        System.exit(0);
    }

}
