package com.imperialm.imimserservices.ssrs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-02T01:29:56.503-04:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", name = "ReportExecutionServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ReportExecutionServiceSoap {

    @WebMethod(operationName = "Render2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render2")
    @RequestWrapper(localName = "Render2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Render2")
    @ResponseWrapper(localName = "Render2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Render2Response")
    public void render2(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        PageCountMode paginationMode,
        @WebParam(mode = WebParam.Mode.OUT, name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<byte[]> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "Extension", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> extension,
        @WebParam(mode = WebParam.Mode.OUT, name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> mimeType,
        @WebParam(mode = WebParam.Mode.OUT, name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> encoding,
        @WebParam(mode = WebParam.Mode.OUT, name = "Warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings,
        @WebParam(mode = WebParam.Mode.OUT, name = "StreamIds", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfString> streamIds
    );

    @WebMethod(operationName = "GetRenderResource", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetRenderResource")
    @RequestWrapper(localName = "GetRenderResource", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetRenderResource")
    @ResponseWrapper(localName = "GetRenderResourceResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetRenderResourceResponse")
    public void getRenderResource(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<byte[]> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> mimeType
    );

    @WebMethod(operationName = "SetExecutionParameters2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters2")
    @RequestWrapper(localName = "SetExecutionParameters2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionParameters2")
    @ResponseWrapper(localName = "SetExecutionParameters2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionParameters2Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public com.imperialm.imimserservices.ssrs.ExecutionInfo2 setExecutionParameters2(
        @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.imperialm.imimserservices.ssrs.ArrayOfParameterValue parameters,
        @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String parameterLanguage
    );

    @WebMethod(operationName = "SetExecutionParameters3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters3")
    @RequestWrapper(localName = "SetExecutionParameters3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionParameters3")
    @ResponseWrapper(localName = "SetExecutionParameters3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionParameters3Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo3 setExecutionParameters3(
        @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfParameterValue parameters,
        @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String parameterLanguage
    );

    @WebMethod(operationName = "LoadDrillthroughTarget", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget")
    @RequestWrapper(localName = "LoadDrillthroughTarget", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadDrillthroughTarget")
    @ResponseWrapper(localName = "LoadDrillthroughTargetResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadDrillthroughTargetResponse")
    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public com.imperialm.imimserservices.ssrs.ExecutionInfo loadDrillthroughTarget(
        @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String drillthroughID
    );

    @WebMethod(operationName = "GetDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetDocumentMap")
    @RequestWrapper(localName = "GetDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetDocumentMap")
    @ResponseWrapper(localName = "GetDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetDocumentMapResponse")
    @WebResult(name = "result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public com.imperialm.imimserservices.ssrs.DocumentMapNode getDocumentMap();

    @WebMethod(operationName = "ListRenderingExtensions", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListRenderingExtensions")
    @RequestWrapper(localName = "ListRenderingExtensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ListRenderingExtensions")
    @ResponseWrapper(localName = "ListRenderingExtensionsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ListRenderingExtensionsResponse")
    @WebResult(name = "Extensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public com.imperialm.imimserservices.ssrs.ArrayOfExtension listRenderingExtensions();

    @WebMethod(operationName = "ListSecureMethods", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListSecureMethods")
    @RequestWrapper(localName = "ListSecureMethods", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ListSecureMethods")
    @ResponseWrapper(localName = "ListSecureMethodsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ListSecureMethodsResponse")
    @WebResult(name = "ListSecureMethodsResult", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public com.imperialm.imimserservices.ssrs.ArrayOfString listSecureMethods();

    @WebMethod(operationName = "ResetExecution3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution3")
    @RequestWrapper(localName = "ResetExecution3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ResetExecution3")
    @ResponseWrapper(localName = "ResetExecution3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ResetExecution3Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo3 resetExecution3();

    @WebMethod(operationName = "SetExecutionParameters", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters")
    @RequestWrapper(localName = "SetExecutionParameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionParameters")
    @ResponseWrapper(localName = "SetExecutionParametersResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionParametersResponse")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo setExecutionParameters(
        @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfParameterValue parameters,
        @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String parameterLanguage
    );

    @WebMethod(operationName = "DeliverReportItem", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/DeliverReportItem")
    @RequestWrapper(localName = "DeliverReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.DeliverReportItem")
    @ResponseWrapper(localName = "DeliverReportItemResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.DeliverReportItemResponse")
    public void deliverReportItem(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(name = "ExtensionSettings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.imperialm.imimserservices.ssrs.ExtensionSettings extensionSettings,
        @WebParam(name = "Description", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String description,
        @WebParam(name = "EventType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String eventType,
        @WebParam(name = "MatchData", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String matchData
    );

    @WebMethod(operationName = "ResetExecution2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution2")
    @RequestWrapper(localName = "ResetExecution2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ResetExecution2")
    @ResponseWrapper(localName = "ResetExecution2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ResetExecution2Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public com.imperialm.imimserservices.ssrs.ExecutionInfo2 resetExecution2();

    @WebMethod(operationName = "Sort2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort2")
    @RequestWrapper(localName = "Sort2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Sort2")
    @ResponseWrapper(localName = "Sort2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Sort2Response")
    public void sort2(
        @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String sortItem,
        @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SortDirectionEnum direction,
        @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        boolean clear,
        @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        PageCountMode paginationMode,
        @WebParam(mode = WebParam.Mode.OUT, name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> pageNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> reportItem,
        @WebParam(mode = WebParam.Mode.OUT, name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ExecutionInfo2> executionInfo
    );

    @WebMethod(operationName = "NavigateBookmark", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateBookmark")
    @RequestWrapper(localName = "NavigateBookmark", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.NavigateBookmark")
    @ResponseWrapper(localName = "NavigateBookmarkResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.NavigateBookmarkResponse")
    public void navigateBookmark(
        @WebParam(name = "BookmarkID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String bookmarkID,
        @WebParam(mode = WebParam.Mode.OUT, name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> pageNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "UniqueName", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> uniqueName
    );

    @WebMethod(operationName = "Sort3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort3")
    @RequestWrapper(localName = "Sort3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Sort3")
    @ResponseWrapper(localName = "Sort3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Sort3Response")
    public void sort3(
        @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String sortItem,
        @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.imperialm.imimserservices.ssrs.SortDirectionEnum direction,
        @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        boolean clear,
        @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        com.imperialm.imimserservices.ssrs.PageCountMode paginationMode,
        @WebParam(mode = WebParam.Mode.OUT, name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> pageNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> reportItem,
        @WebParam(mode = WebParam.Mode.OUT, name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ExecutionInfo3> executionInfo
    );

    @WebMethod(operationName = "Logoff", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Logoff")
    @RequestWrapper(localName = "Logoff", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Logoff")
    @ResponseWrapper(localName = "LogoffResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LogoffResponse")
    public void logoff();

    @WebMethod(operationName = "LoadReport", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport")
    @RequestWrapper(localName = "LoadReport", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReport")
    @ResponseWrapper(localName = "LoadReportResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReportResponse")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo loadReport(
        @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String report,
        @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String historyID
    );

    @WebMethod(operationName = "LoadReportDefinition", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition")
    @RequestWrapper(localName = "LoadReportDefinition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReportDefinition")
    @ResponseWrapper(localName = "LoadReportDefinitionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReportDefinitionResponse")
    public void loadReportDefinition(
        @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        byte[] definition,
        @WebParam(mode = WebParam.Mode.OUT, name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ExecutionInfo> executionInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings
    );

    @WebMethod(operationName = "LoadReport2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport2")
    @RequestWrapper(localName = "LoadReport2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReport2")
    @ResponseWrapper(localName = "LoadReport2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReport2Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public com.imperialm.imimserservices.ssrs.ExecutionInfo2 loadReport2(
        @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String report,
        @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String historyID
    );

    @WebMethod(operationName = "LoadReport3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport3")
    @RequestWrapper(localName = "LoadReport3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReport3")
    @ResponseWrapper(localName = "LoadReport3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReport3Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo3 loadReport3(
        @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String report,
        @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String historyID
    );

    @WebMethod(operationName = "LoadDrillthroughTarget3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget3")
    @RequestWrapper(localName = "LoadDrillthroughTarget3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadDrillthroughTarget3")
    @ResponseWrapper(localName = "LoadDrillthroughTarget3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadDrillthroughTarget3Response")
    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo3 loadDrillthroughTarget3(
        @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String drillthroughID
    );

    @WebMethod(operationName = "LoadDrillthroughTarget2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget2")
    @RequestWrapper(localName = "LoadDrillthroughTarget2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadDrillthroughTarget2")
    @ResponseWrapper(localName = "LoadDrillthroughTarget2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadDrillthroughTarget2Response")
    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public com.imperialm.imimserservices.ssrs.ExecutionInfo2 loadDrillthroughTarget2(
        @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String drillthroughID
    );

    @WebMethod(operationName = "NavigateDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateDocumentMap")
    @RequestWrapper(localName = "NavigateDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.NavigateDocumentMap")
    @ResponseWrapper(localName = "NavigateDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.NavigateDocumentMapResponse")
    @WebResult(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public int navigateDocumentMap(
        @WebParam(name = "DocMapID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String docMapID
    );

    @WebMethod(operationName = "SetExecutionCredentials3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials3")
    @RequestWrapper(localName = "SetExecutionCredentials3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionCredentials3")
    @ResponseWrapper(localName = "SetExecutionCredentials3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionCredentials3Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo3 setExecutionCredentials3(
        @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfDataSourceCredentials credentials
    );

    @WebMethod(operationName = "SetExecutionCredentials2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials2")
    @RequestWrapper(localName = "SetExecutionCredentials2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionCredentials2")
    @ResponseWrapper(localName = "SetExecutionCredentials2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionCredentials2Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo2 setExecutionCredentials2(
        @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfDataSourceCredentials credentials
    );

    @WebMethod(operationName = "Render", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render")
    @RequestWrapper(localName = "Render", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Render")
    @ResponseWrapper(localName = "RenderResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.RenderResponse")
    public void render(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<byte[]> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "Extension", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> extension,
        @WebParam(mode = WebParam.Mode.OUT, name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> mimeType,
        @WebParam(mode = WebParam.Mode.OUT, name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> encoding,
        @WebParam(mode = WebParam.Mode.OUT, name = "Warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings,
        @WebParam(mode = WebParam.Mode.OUT, name = "StreamIds", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfString> streamIds
    );

    @WebMethod(operationName = "GetExecutionInfo", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo")
    @RequestWrapper(localName = "GetExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetExecutionInfo")
    @ResponseWrapper(localName = "GetExecutionInfoResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetExecutionInfoResponse")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo getExecutionInfo();

    @WebMethod(operationName = "LoadReportDefinition3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition3")
    @RequestWrapper(localName = "LoadReportDefinition3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReportDefinition3")
    @ResponseWrapper(localName = "LoadReportDefinition3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReportDefinition3Response")
    public void loadReportDefinition3(
        @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        byte[] definition,
        @WebParam(mode = WebParam.Mode.OUT, name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ExecutionInfo3> executionInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings
    );

    @WebMethod(operationName = "FindString", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/FindString")
    @RequestWrapper(localName = "FindString", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.FindString")
    @ResponseWrapper(localName = "FindStringResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.FindStringResponse")
    @WebResult(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public int findString(
        @WebParam(name = "StartPage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        int startPage,
        @WebParam(name = "EndPage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        int endPage,
        @WebParam(name = "FindValue", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String findValue
    );

    @WebMethod(operationName = "LogonUser", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LogonUser")
    @RequestWrapper(localName = "LogonUser", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LogonUser")
    @ResponseWrapper(localName = "LogonUserResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LogonUserResponse")
    public void logonUser(
        @WebParam(name = "userName", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String password,
        @WebParam(name = "authority", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String authority
    );

    @WebMethod(operationName = "ToggleItem", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ToggleItem")
    @RequestWrapper(localName = "ToggleItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ToggleItem")
    @ResponseWrapper(localName = "ToggleItemResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ToggleItemResponse")
    @WebResult(name = "Found", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public boolean toggleItem(
        @WebParam(name = "ToggleID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String toggleID
    );

    @WebMethod(operationName = "Sort", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort")
    @RequestWrapper(localName = "Sort", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.Sort")
    @ResponseWrapper(localName = "SortResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SortResponse")
    public void sort(
        @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String sortItem,
        @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        SortDirectionEnum direction,
        @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        boolean clear,
        @WebParam(mode = WebParam.Mode.OUT, name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> pageNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> reportItem,
        @WebParam(mode = WebParam.Mode.OUT, name = "NumPages", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.Integer> numPages
    );

    @WebMethod(operationName = "LoadReportDefinition2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition2")
    @RequestWrapper(localName = "LoadReportDefinition2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReportDefinition2")
    @ResponseWrapper(localName = "LoadReportDefinition2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.LoadReportDefinition2Response")
    public void loadReportDefinition2(
        @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        byte[] definition,
        @WebParam(mode = WebParam.Mode.OUT, name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ExecutionInfo2> executionInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<ArrayOfWarning> warnings
    );

    @WebMethod(operationName = "ResetExecution", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution")
    @RequestWrapper(localName = "ResetExecution", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ResetExecution")
    @ResponseWrapper(localName = "ResetExecutionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.ResetExecutionResponse")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo resetExecution();

    @WebMethod(operationName = "SetExecutionCredentials", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials")
    @RequestWrapper(localName = "SetExecutionCredentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionCredentials")
    @ResponseWrapper(localName = "SetExecutionCredentialsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.SetExecutionCredentialsResponse")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo setExecutionCredentials(
        @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        ArrayOfDataSourceCredentials credentials
    );

    @WebMethod(operationName = "GetExecutionInfo3", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo3")
    @RequestWrapper(localName = "GetExecutionInfo3", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetExecutionInfo3")
    @ResponseWrapper(localName = "GetExecutionInfo3Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetExecutionInfo3Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo3 getExecutionInfo3();

    @WebMethod(operationName = "GetExecutionInfo2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo2")
    @RequestWrapper(localName = "GetExecutionInfo2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetExecutionInfo2")
    @ResponseWrapper(localName = "GetExecutionInfo2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.GetExecutionInfo2Response")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    public ExecutionInfo2 getExecutionInfo2();

    @WebMethod(operationName = "RenderStream", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/RenderStream")
    @RequestWrapper(localName = "RenderStream", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.RenderStream")
    @ResponseWrapper(localName = "RenderStreamResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.imperialm.imimserservices.ssrs.RenderStreamResponse")
    public void renderStream(
        @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String format,
        @WebParam(name = "StreamID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String streamID,
        @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        java.lang.String deviceInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<byte[]> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> encoding,
        @WebParam(mode = WebParam.Mode.OUT, name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
        javax.xml.ws.Holder<java.lang.String> mimeType
    );
}
