
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.imperialm.imimserservices.ssrs;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-02T01:29:56.403-04:00
 * Generated source version: 3.1.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "ReportExecutionService",
                      portName = "ReportExecutionServiceSoap",
                      targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices",
                      wsdlLocation = "file:/C:/Users/Ali/Desktop/ReportExecution2005.xml",
                      endpointInterface = "com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap")
                      
public class ReportExecutionServiceSoapImpl implements ReportExecutionServiceSoap {

    private static final Logger LOG = Logger.getLogger(ReportExecutionServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#render2(java.lang.String format, java.lang.String deviceInfo, com.imperialm.imimserservices.ssrs.PageCountMode paginationMode, byte[] result, java.lang.String extension, java.lang.String mimeType, java.lang.String encoding, com.imperialm.imimserservices.ssrs.ArrayOfWarning warnings, com.imperialm.imimserservices.ssrs.ArrayOfString streamIds)*
     */
    public void render2(java.lang.String format, java.lang.String deviceInfo, PageCountMode paginationMode, javax.xml.ws.Holder<byte[]> result, javax.xml.ws.Holder<java.lang.String> extension, javax.xml.ws.Holder<java.lang.String> mimeType, javax.xml.ws.Holder<java.lang.String> encoding, javax.xml.ws.Holder<ArrayOfWarning> warnings, javax.xml.ws.Holder<ArrayOfString> streamIds) { 
        LOG.info("Executing operation render2");
        System.out.println(format);
        System.out.println(deviceInfo);
        System.out.println(paginationMode);
        try {
            byte[] resultValue = new byte[0];
            result.value = resultValue;
            java.lang.String extensionValue = "";
            extension.value = extensionValue;
            java.lang.String mimeTypeValue = "";
            mimeType.value = mimeTypeValue;
            java.lang.String encodingValue = "";
            encoding.value = encodingValue;
            ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
            ArrayOfString streamIdsValue = null;
            streamIds.value = streamIdsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#getRenderResource(java.lang.String format, java.lang.String deviceInfo, byte[] result, java.lang.String mimeType)*
     */
    public void getRenderResource(java.lang.String format, java.lang.String deviceInfo, javax.xml.ws.Holder<byte[]> result, javax.xml.ws.Holder<java.lang.String> mimeType) { 
        LOG.info("Executing operation getRenderResource");
        System.out.println(format);
        System.out.println(deviceInfo);
        try {
            byte[] resultValue = new byte[0];
            result.value = resultValue;
            java.lang.String mimeTypeValue = "";
            mimeType.value = mimeTypeValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#setExecutionParameters2(com.imperialm.imimserservices.ssrs.ArrayOfParameterValue parameters, java.lang.String parameterLanguage)*
     */
    public com.imperialm.imimserservices.ssrs.ExecutionInfo2 setExecutionParameters2(com.imperialm.imimserservices.ssrs.ArrayOfParameterValue parameters, java.lang.String parameterLanguage) { 
        LOG.info("Executing operation setExecutionParameters2");
        System.out.println(parameters);
        System.out.println(parameterLanguage);
        try {
            com.imperialm.imimserservices.ssrs.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#setExecutionParameters3(com.imperialm.imimserservices.ssrs.ArrayOfParameterValue parameters, java.lang.String parameterLanguage)*
     */
    public ExecutionInfo3 setExecutionParameters3(ArrayOfParameterValue parameters, java.lang.String parameterLanguage) { 
        LOG.info("Executing operation setExecutionParameters3");
        System.out.println(parameters);
        System.out.println(parameterLanguage);
        try {
            ExecutionInfo3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadDrillthroughTarget(java.lang.String drillthroughID)*
     */
    public com.imperialm.imimserservices.ssrs.ExecutionInfo loadDrillthroughTarget(java.lang.String drillthroughID) { 
        LOG.info("Executing operation loadDrillthroughTarget");
        System.out.println(drillthroughID);
        try {
            com.imperialm.imimserservices.ssrs.ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#getDocumentMap()*
     */
    public com.imperialm.imimserservices.ssrs.DocumentMapNode getDocumentMap() { 
        LOG.info("Executing operation getDocumentMap");
        try {
            com.imperialm.imimserservices.ssrs.DocumentMapNode _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#listRenderingExtensions()*
     */
    public com.imperialm.imimserservices.ssrs.ArrayOfExtension listRenderingExtensions() { 
        LOG.info("Executing operation listRenderingExtensions");
        try {
            com.imperialm.imimserservices.ssrs.ArrayOfExtension _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#listSecureMethods()*
     */
    public com.imperialm.imimserservices.ssrs.ArrayOfString listSecureMethods() { 
        LOG.info("Executing operation listSecureMethods");
        try {
            com.imperialm.imimserservices.ssrs.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#resetExecution3()*
     */
    public com.imperialm.imimserservices.ssrs.ExecutionInfo3 resetExecution3() { 
        LOG.info("Executing operation resetExecution3");
        try {
            com.imperialm.imimserservices.ssrs.ExecutionInfo3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#setExecutionParameters(com.imperialm.imimserservices.ssrs.ArrayOfParameterValue parameters, java.lang.String parameterLanguage)*
     */
    public ExecutionInfo setExecutionParameters(ArrayOfParameterValue parameters, java.lang.String parameterLanguage) { 
        LOG.info("Executing operation setExecutionParameters");
        System.out.println(parameters);
        System.out.println(parameterLanguage);
        try {
            ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#deliverReportItem(java.lang.String format, java.lang.String deviceInfo, com.imperialm.imimserservices.ssrs.ExtensionSettings extensionSettings, java.lang.String description, java.lang.String eventType, java.lang.String matchData)*
     */
    public void deliverReportItem(java.lang.String format, java.lang.String deviceInfo, com.imperialm.imimserservices.ssrs.ExtensionSettings extensionSettings, java.lang.String description, java.lang.String eventType, java.lang.String matchData) { 
        LOG.info("Executing operation deliverReportItem");
        System.out.println(format);
        System.out.println(deviceInfo);
        System.out.println(extensionSettings);
        System.out.println(description);
        System.out.println(eventType);
        System.out.println(matchData);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#resetExecution2()*
     */
    public com.imperialm.imimserservices.ssrs.ExecutionInfo2 resetExecution2() { 
        LOG.info("Executing operation resetExecution2");
        try {
            com.imperialm.imimserservices.ssrs.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#sort2(java.lang.String sortItem, com.imperialm.imimserservices.ssrs.SortDirectionEnum direction, boolean clear, com.imperialm.imimserservices.ssrs.PageCountMode paginationMode, java.lang.Integer pageNumber, java.lang.String reportItem, com.imperialm.imimserservices.ssrs.ExecutionInfo2 executionInfo)*
     */
    public void sort2(String sortItem, SortDirectionEnum direction, boolean clear, PageCountMode paginationMode, javax.xml.ws.Holder<java.lang.Integer> pageNumber, javax.xml.ws.Holder<java.lang.String> reportItem, javax.xml.ws.Holder<ExecutionInfo2> executionInfo) { 
        LOG.info("Executing operation sort2");
        System.out.println(sortItem);
        System.out.println(direction);
        System.out.println(clear);
        System.out.println(paginationMode);
        try {
            java.lang.Integer pageNumberValue = null;
            pageNumber.value = pageNumberValue;
            java.lang.String reportItemValue = "";
            reportItem.value = reportItemValue;
            ExecutionInfo2 executionInfoValue = null;
            executionInfo.value = executionInfoValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#navigateBookmark(java.lang.String bookmarkID, java.lang.Integer pageNumber, java.lang.String uniqueName)*
     */
    public void navigateBookmark(java.lang.String bookmarkID, javax.xml.ws.Holder<java.lang.Integer> pageNumber, javax.xml.ws.Holder<java.lang.String> uniqueName) { 
        LOG.info("Executing operation navigateBookmark");
        System.out.println(bookmarkID);
        try {
            java.lang.Integer pageNumberValue = null;
            pageNumber.value = pageNumberValue;
            java.lang.String uniqueNameValue = "";
            uniqueName.value = uniqueNameValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#sort3(java.lang.String sortItem, com.imperialm.imimserservices.ssrs.SortDirectionEnum direction, boolean clear, com.imperialm.imimserservices.ssrs.PageCountMode paginationMode, java.lang.Integer pageNumber, java.lang.String reportItem, com.imperialm.imimserservices.ssrs.ExecutionInfo3 executionInfo)*
     */
    public void sort3(java.lang.String sortItem, com.imperialm.imimserservices.ssrs.SortDirectionEnum direction, boolean clear, com.imperialm.imimserservices.ssrs.PageCountMode paginationMode, javax.xml.ws.Holder<java.lang.Integer> pageNumber, javax.xml.ws.Holder<java.lang.String> reportItem, javax.xml.ws.Holder<ExecutionInfo3> executionInfo) { 
        LOG.info("Executing operation sort3");
        System.out.println(sortItem);
        System.out.println(direction);
        System.out.println(clear);
        System.out.println(paginationMode);
        try {
            java.lang.Integer pageNumberValue = null;
            pageNumber.value = pageNumberValue;
            java.lang.String reportItemValue = "";
            reportItem.value = reportItemValue;
            ExecutionInfo3 executionInfoValue = null;
            executionInfo.value = executionInfoValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#logoff()*
     */
    public void logoff() { 
        LOG.info("Executing operation logoff");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadReport(java.lang.String report, java.lang.String historyID)*
     */
    public ExecutionInfo loadReport(java.lang.String report, java.lang.String historyID) { 
        LOG.info("Executing operation loadReport");
        System.out.println(report);
        System.out.println(historyID);
        try {
            ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadReportDefinition(byte[] definition, com.imperialm.imimserservices.ssrs.ExecutionInfo executionInfo, com.imperialm.imimserservices.ssrs.ArrayOfWarning warnings)*
     */
    public void loadReportDefinition(byte[] definition, javax.xml.ws.Holder<ExecutionInfo> executionInfo, javax.xml.ws.Holder<ArrayOfWarning> warnings) { 
        LOG.info("Executing operation loadReportDefinition");
        System.out.println(definition);
        try {
            ExecutionInfo executionInfoValue = null;
            executionInfo.value = executionInfoValue;
            ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadReport2(java.lang.String report, java.lang.String historyID)*
     */
    public com.imperialm.imimserservices.ssrs.ExecutionInfo2 loadReport2(java.lang.String report, java.lang.String historyID) { 
        LOG.info("Executing operation loadReport2");
        System.out.println(report);
        System.out.println(historyID);
        try {
            com.imperialm.imimserservices.ssrs.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadReport3(java.lang.String report, java.lang.String historyID)*
     */
    public com.imperialm.imimserservices.ssrs.ExecutionInfo3 loadReport3(java.lang.String report, java.lang.String historyID) { 
        LOG.info("Executing operation loadReport3");
        System.out.println(report);
        System.out.println(historyID);
        try {
            com.imperialm.imimserservices.ssrs.ExecutionInfo3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadDrillthroughTarget3(java.lang.String drillthroughID)*
     */
    public com.imperialm.imimserservices.ssrs.ExecutionInfo3 loadDrillthroughTarget3(java.lang.String drillthroughID) { 
        LOG.info("Executing operation loadDrillthroughTarget3");
        System.out.println(drillthroughID);
        try {
            com.imperialm.imimserservices.ssrs.ExecutionInfo3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadDrillthroughTarget2(java.lang.String drillthroughID)*
     */
    public com.imperialm.imimserservices.ssrs.ExecutionInfo2 loadDrillthroughTarget2(java.lang.String drillthroughID) { 
        LOG.info("Executing operation loadDrillthroughTarget2");
        System.out.println(drillthroughID);
        try {
            com.imperialm.imimserservices.ssrs.ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#navigateDocumentMap(java.lang.String docMapID)*
     */
    public int navigateDocumentMap(java.lang.String docMapID) { 
        LOG.info("Executing operation navigateDocumentMap");
        System.out.println(docMapID);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#setExecutionCredentials3(com.imperialm.imimserservices.ssrs.ArrayOfDataSourceCredentials credentials)*
     */
    public ExecutionInfo3 setExecutionCredentials3(ArrayOfDataSourceCredentials credentials) { 
        LOG.info("Executing operation setExecutionCredentials3");
        System.out.println(credentials);
        try {
            ExecutionInfo3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#setExecutionCredentials2(com.imperialm.imimserservices.ssrs.ArrayOfDataSourceCredentials credentials)*
     */
    public ExecutionInfo2 setExecutionCredentials2(ArrayOfDataSourceCredentials credentials) { 
        LOG.info("Executing operation setExecutionCredentials2");
        System.out.println(credentials);
        try {
            ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#render(java.lang.String format, java.lang.String deviceInfo, byte[] result, java.lang.String extension, java.lang.String mimeType, java.lang.String encoding, com.imperialm.imimserservices.ssrs.ArrayOfWarning warnings, com.imperialm.imimserservices.ssrs.ArrayOfString streamIds)*
     */
    public void render(java.lang.String format, java.lang.String deviceInfo, javax.xml.ws.Holder<byte[]> result, javax.xml.ws.Holder<java.lang.String> extension, javax.xml.ws.Holder<java.lang.String> mimeType, javax.xml.ws.Holder<java.lang.String> encoding, javax.xml.ws.Holder<ArrayOfWarning> warnings, javax.xml.ws.Holder<ArrayOfString> streamIds) { 
        LOG.info("Executing operation render");
        System.out.println(format);
        System.out.println(deviceInfo);
        try {
            byte[] resultValue = new byte[0];
            result.value = resultValue;
            java.lang.String extensionValue = "";
            extension.value = extensionValue;
            java.lang.String mimeTypeValue = "";
            mimeType.value = mimeTypeValue;
            java.lang.String encodingValue = "";
            encoding.value = encodingValue;
            ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
            ArrayOfString streamIdsValue = null;
            streamIds.value = streamIdsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#getExecutionInfo()*
     */
    public ExecutionInfo getExecutionInfo() { 
        LOG.info("Executing operation getExecutionInfo");
        try {
            ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadReportDefinition3(byte[] definition, com.imperialm.imimserservices.ssrs.ExecutionInfo3 executionInfo, com.imperialm.imimserservices.ssrs.ArrayOfWarning warnings)*
     */
    public void loadReportDefinition3(byte[] definition, javax.xml.ws.Holder<ExecutionInfo3> executionInfo, javax.xml.ws.Holder<ArrayOfWarning> warnings) { 
        LOG.info("Executing operation loadReportDefinition3");
        System.out.println(definition);
        try {
            ExecutionInfo3 executionInfoValue = null;
            executionInfo.value = executionInfoValue;
            ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#findString(int startPage, int endPage, java.lang.String findValue)*
     */
    public int findString(int startPage, int endPage, java.lang.String findValue) { 
        LOG.info("Executing operation findString");
        System.out.println(startPage);
        System.out.println(endPage);
        System.out.println(findValue);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#logonUser(java.lang.String userName, java.lang.String password, java.lang.String authority)*
     */
    public void logonUser(java.lang.String userName, java.lang.String password, java.lang.String authority) { 
        LOG.info("Executing operation logonUser");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(authority);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#toggleItem(java.lang.String toggleID)*
     */
    public boolean toggleItem(java.lang.String toggleID) { 
        LOG.info("Executing operation toggleItem");
        System.out.println(toggleID);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#sort(java.lang.String sortItem, com.imperialm.imimserservices.ssrs.SortDirectionEnum direction, boolean clear, java.lang.Integer pageNumber, java.lang.String reportItem, java.lang.Integer numPages)*
     */
    public void sort(java.lang.String sortItem, SortDirectionEnum direction, boolean clear, javax.xml.ws.Holder<java.lang.Integer> pageNumber, javax.xml.ws.Holder<java.lang.String> reportItem, javax.xml.ws.Holder<java.lang.Integer> numPages) { 
        LOG.info("Executing operation sort");
        System.out.println(sortItem);
        System.out.println(direction);
        System.out.println(clear);
        try {
            java.lang.Integer pageNumberValue = null;
            pageNumber.value = pageNumberValue;
            java.lang.String reportItemValue = "";
            reportItem.value = reportItemValue;
            java.lang.Integer numPagesValue = null;
            numPages.value = numPagesValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#loadReportDefinition2(byte[] definition, com.imperialm.imimserservices.ssrs.ExecutionInfo2 executionInfo, com.imperialm.imimserservices.ssrs.ArrayOfWarning warnings)*
     */
    public void loadReportDefinition2(byte[] definition, javax.xml.ws.Holder<ExecutionInfo2> executionInfo, javax.xml.ws.Holder<ArrayOfWarning> warnings) { 
        LOG.info("Executing operation loadReportDefinition2");
        System.out.println(definition);
        try {
            ExecutionInfo2 executionInfoValue = null;
            executionInfo.value = executionInfoValue;
            ArrayOfWarning warningsValue = null;
            warnings.value = warningsValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#resetExecution()*
     */
    public ExecutionInfo resetExecution() { 
        LOG.info("Executing operation resetExecution");
        try {
            ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#setExecutionCredentials(com.imperialm.imimserservices.ssrs.ArrayOfDataSourceCredentials credentials)*
     */
    public ExecutionInfo setExecutionCredentials(ArrayOfDataSourceCredentials credentials) { 
        LOG.info("Executing operation setExecutionCredentials");
        System.out.println(credentials);
        try {
            ExecutionInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#getExecutionInfo3()*
     */
    public ExecutionInfo3 getExecutionInfo3() { 
        LOG.info("Executing operation getExecutionInfo3");
        try {
            ExecutionInfo3 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#getExecutionInfo2()*
     */
    public ExecutionInfo2 getExecutionInfo2() { 
        LOG.info("Executing operation getExecutionInfo2");
        try {
            ExecutionInfo2 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.imperialm.imimserservices.ssrs.ReportExecutionServiceSoap#renderStream(java.lang.String format, java.lang.String streamID, java.lang.String deviceInfo, byte[] result, java.lang.String encoding, java.lang.String mimeType)*
     */
    public void renderStream(java.lang.String format, java.lang.String streamID, java.lang.String deviceInfo, javax.xml.ws.Holder<byte[]> result, javax.xml.ws.Holder<java.lang.String> encoding, javax.xml.ws.Holder<java.lang.String> mimeType) { 
        LOG.info("Executing operation renderStream");
        System.out.println(format);
        System.out.println(streamID);
        System.out.println(deviceInfo);
        try {
            byte[] resultValue = new byte[0];
            result.value = resultValue;
            java.lang.String encodingValue = "";
            encoding.value = encodingValue;
            java.lang.String mimeTypeValue = "";
            mimeType.value = mimeTypeValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }


}
